"""Gatekeeper HTTP API — create/inspect/control realms over REST + a minimal dashboard (#19).

Read endpoints query the Chronicle (the read-model everything already writes to); control
endpoints (create/stop/msg) drive the RealmManager + Herald. Serves a self-contained dashboard
at `/`. Run with: `uvicorn agentrealm.gatekeeper.api:app` (or `arealm serve`).
"""

from __future__ import annotations

import contextlib
import json
import logging
import os
import re
import secrets
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from fastapi import Body, FastAPI, File, HTTPException, Request, UploadFile
from fastapi.responses import HTMLResponse, JSONResponse, Response, StreamingResponse
from pydantic import BaseModel, ValidationError
from starlette.middleware.trustedhost import TrustedHostMiddleware

from agentrealm.chronicle import Chronicle, EventKind
from agentrealm.core import PackageError, Turns, load_package
from agentrealm.core.colors import resolve_agent_colors
from agentrealm.core.schema import Project
from agentrealm.gatekeeper import scenarios as sc
from agentrealm.gatekeeper.auth import (
    COOKIE_NAME,
    QUERY_PARAM,
    is_public_path,
    load_or_create_token,
    presented_token,
    token_matches,
)
from agentrealm.gatekeeper.manager import CapacityError, RealmManager
from agentrealm.gatekeeper.service import build_platform
from agentrealm.scribe.backend import DEFAULT_MODEL, LLMBackend
from agentrealm.scribe.history import HistoryStore, compact
from agentrealm.scribe.loop import ScribeLoop
from agentrealm.scribe.service import ScribeSession, build_scribe, visible_history
from agentrealm.scribe.store import ApiPackageStore, PackageStore
from agentrealm.scribe.validate import validate_scenario as scribe_validate
from agentrealm.scribe.versions import Versions

STATIC_DIR = Path(__file__).parent / "static"  # the multi-page UI (index.html, app.css, app.js)
_JSON_BODY: Any = Body(...)  # module-level singleton (FastAPI body marker; avoids ruff B008)

# realm states that mean "still going" — only valid while the manager has a live task
NON_TERMINAL = ("provisioning", "running", "concluding")


def _import_base() -> Path:
    """Where uploaded scenario folders are stored (persists across restarts)."""
    return Path(
        os.environ.get("AGENTREALM_SCENARIOS_DIR", str(Path.home() / ".agentrealm" / "scenarios"))
    )


def _scenario_bases() -> list[Path]:
    """Dirs scanned for scenario packages, in precedence order: the writable user dir first (so
    edits shadow a bundled template of the same name), then the read-only examples."""
    return [_import_base(), Path(os.environ.get("AGENTREALM_EXAMPLES_DIR", "examples"))]


def _find_scenario(name: str) -> Path | None:
    for base in _scenario_bases():
        path = base / name
        if (path / "project.json").exists():
            return path
    return None


class TurnsConfig(BaseModel):
    """Run-time turn-taking override from the launch UI. Absent = use the scenario's own policy."""

    enabled: bool = False
    silence_timeout_s: float = 90.0


class CreateRealm(BaseModel):
    package: str  # path to a project package or flat manifest
    realm_id: str | None = None
    free_response: bool = False
    turns: TurnsConfig | None = None  # override the scenario's turn policy for this run


class ScribeSessionCreate(BaseModel):
    mode: str  # "create" (guided wizard) | "edit" (bound to one scenario)
    scenario: str | None = None  # [edit] which scenario the session edits


class ScribeMessage(BaseModel):
    session_id: str  # server-generated by POST /api/scribe/session
    text: str


class ScribeApprove(BaseModel):
    session_id: str


class Inject(BaseModel):
    text: str
    to: str | None = None  # an agent mxid (or bare id) to address; null = all agents


log = logging.getLogger(__name__)


async def reconcile_orphans(chron: Chronicle) -> int:
    """On startup, no realm can still be running (the manager starts empty). Any realm whose last
    lifecycle event is non-terminal was cut off by a restart — record an 'interrupted' event so
    its state is honest. Returns how many were reconciled."""
    n = 0
    for realm_id in await chron.realms():
        lifecycle = await chron.events(realm_id, kind=EventKind.LIFECYCLE)
        if lifecycle and lifecycle[-1].payload.get("event") in NON_TERMINAL:
            await chron.append_event(
                realm_id, EventKind.LIFECYCLE, {"event": "interrupted", "detail": "server restart"}
            )
            n += 1
    return n


def _skill_content(source: str, ref: str, pkg_path: str) -> str:
    """The SKILL.md text for a skill ref, so the UI can show it: built-ins from the library,
    local skills read from the package. External (github) skills aren't resolvable here."""
    if source == "builtin":
        from agentrealm.forge.skills import BUILTIN_SKILLS
        return BUILTIN_SKILLS.get(ref, "")
    if source == "local":
        import pathlib
        try:
            return (pathlib.Path(pkg_path) / "skills" / ref / "SKILL.md").read_text()
        except OSError:
            return ""
    return ""


def serialize_project(project: Any, name: str, path: str) -> dict[str, Any]:
    """A display-friendly view of a scenario: config + roster, for the preview page."""
    md, spec, env = project.metadata, project.spec, project.spec.environment
    ref = project.referee
    skill_contents: dict[str, str] = {}  # "source:ref" -> SKILL.md text (deduped across agents)
    for a in project.agents:
        for sk in a.skills:
            key = f"{sk.source}:{sk.ref}"
            if key not in skill_contents:
                content = _skill_content(str(sk.source), sk.ref, path)
                if content:
                    skill_contents[key] = content
    # roster in display order (referee first), and each agent's resolved message color
    roster = sorted(project.agents, key=lambda a: 0 if ref and a.id == ref.id else 1)
    colors = resolve_agent_colors(roster)
    return {
        "name": name, "path": path, "title": md.name, "description": md.description or "",
        "tags": list(md.tags or []), "author": md.author or "", "category": md.category or "",
        "goals": list(spec.goals or []), "guidelines": spec.guidelines or "",
        "restrictions": spec.restrictions or "",
        "environment": {
            "network_egress": str(env.network_egress),
            "shared_folder": bool(env.shared_folder.enabled),
            "require_mention": bool(env.require_mention),
            "allow_side_channels": bool(env.allow_side_channels),
            "egress_allowlist": list(env.egress_allowlist or []),
        },
        "referee_opens": bool(spec.referee_opens),
        "provide_tools": bool(spec.provide_tools),
        "stall_nudge": bool(spec.stall_nudge),
        "mechanics": [m.model_dump(mode="json") for m in spec.mechanics],
        "turns": spec.turns.model_dump(mode="json") if spec.turns is not None else None,
        "termination": [
            {k: v for k, v in t.model_dump(mode="json").items() if v is not None}
            for t in spec.termination
        ],
        "referee": ref.id if ref else None,
        # referee first (stable otherwise) — the host/adjudicator heads the roster in the UI
        "agents": [
            {
                "id": a.id, "name": a.name or a.id, "role": str(a.role),
                "color": colors[a.id],
                "persona": a.persona or "", "goals": list(a.goals or []),
                "responsibilities": list(a.responsibilities or []), "rubric": a.rubric or "",
                # the capability tier the agent asks for; the active provider resolves it at launch
                "model_category": str(a.model_category),
                "model": str(a.model_category),
                "budget": a.budget.max_usd,
                # an optional exact-model override (null for category-based agents) — round-trips
                "model_ref": a.model.model_dump(mode="json") if a.model else None,
                "budget_ref": a.budget.model_dump(mode="json"),
                "private_messaging": a.private_messaging.model_dump(mode="json"),
                "skills": [f"{sk.source}:{sk.ref}" for sk in a.skills],
            }
            for a in roster
        ],
        "skill_contents": skill_contents,
    }


async def realm_status(chron: Chronicle, realm_id: str) -> dict[str, Any]:
    events = await chron.events(realm_id)
    if not events:
        raise HTTPException(status_code=404, detail=f"no such realm {realm_id!r}")
    lifecycle = [e for e in events if e.kind == EventKind.LIFECYCLE]
    state = lifecycle[-1].payload.get("event") if lifecycle else "unknown"
    # the RESOLVED configuration this run used (models, turns, budgets) — captured at launch
    config: dict[str, Any] = next(
        (e.payload["config"] for e in lifecycle if e.payload.get("config")), {}
    )
    spend: dict[str, float] = {}
    tokens: dict[str, int] = {}  # agent -> total tokens (prompt + completion)
    ledger: dict[str, float] = {}  # running score = raw re-sum of SCORE-event deltas
    verdict_board: dict[str, float] | None = None  # the arbiter board the referee RULED on
    violations: list[dict[str, Any]] = []
    outcome = None
    for e in events:
        p = e.payload
        if e.kind == EventKind.SPEND and "agent" in p:
            spend[p["agent"]] = round(spend.get(p["agent"], 0.0) + float(p.get("usd", 0)), 6)
            tokens[p["agent"]] = tokens.get(p["agent"], 0) + int(p.get("tokens_in", 0) or 0) \
                + int(p.get("tokens_out", 0) or 0)
        elif e.kind == EventKind.SCORE and "agent" in p:
            ledger[p["agent"]] = round(ledger.get(p["agent"], 0.0) + float(p.get("delta", 0)), 6)
        elif e.kind == EventKind.VIOLATION and "agent" in p:
            violations.append({"agent": p["agent"], "reason": p.get("reason", "")})
        elif e.kind == EventKind.VERDICT:
            outcome = p.get("outcome", outcome)
            sb = p.get("scoreboard")
            if isinstance(sb, dict) and sb:  # the referee's ruling carries its own scoreboard
                verdict_board = {k: round(float(v), 6) for k, v in sb.items()}
    # Once the referee has RULED, its recorded scoreboard is the score of record — not a re-sum of
    # raw SCORE events. Those two normally agree, but the re-sum can be corrupted by a duplicate
    # SCORE write (rps-rv1: a spurious second 'round R1' event inflated the ledger to 3-2 while the
    # referee's own board, outcome, and reasons all said 2-2). Physics-vs-law: the referee's verdict
    # is law, so once it exists we surface its board and flag — not hide — any divergence.
    scores = verdict_board if verdict_board is not None else ledger
    score_discrepancy = verdict_board is not None and verdict_board != ledger
    msgs = await chron.messages(realm_id)
    return {
        "realm_id": realm_id, "state": state, "outcome": outcome,
        "config": config,
        "spend": spend, "total_spend": round(sum(spend.values()), 6),
        "tokens": tokens, "total_tokens": sum(tokens.values()),
        "scores": scores, "score_ledger": ledger, "score_discrepancy": score_discrepancy,
        "violations": violations,
        "messages": len(msgs), "events": len(events),
    }


def _allowed_hosts() -> list[str]:
    """Host headers this control plane will answer to.

    `testserver` is Starlette's TestClient host. Set AGENTREALM_ALLOWED_HOSTS to a comma-separated
    list to serve on a real hostname; "*" disables the check, which is only safe on a host nobody
    else can reach.
    """
    configured = os.environ.get("AGENTREALM_ALLOWED_HOSTS", "").strip()
    if configured:
        return [h.strip() for h in configured.split(",") if h.strip()]
    return ["localhost", "127.0.0.1", "[::1]", "testserver"]


def create_app(
    *,
    chron: Chronicle | None = None,
    manager: RealmManager | None = None,
    scribe_backend: LLMBackend | None = None,
    scribe_store: PackageStore | None = None,
    scribe_root: Path | None = None,
    auth_token: str | None = None,
) -> FastAPI:
    """Build the app. Prod: pass nothing — the lifespan builds the Platform, and the API token is
    loaded (or generated) from ~/.agentrealm/api-token. Tests: inject a chronicle (+ optional
    manager) to exercise the read/control endpoints without the stack, and a scribe backend/store/
    root to exercise the guided-authoring endpoints with no model calls.

    `auth_token` gates every /api/* route. An INJECTED app defaults to no token, because a test
    asserting an endpoint's behaviour should not have to re-assert the auth wrapper each time —
    `tests/test_api_auth.py` builds an app WITH a token and covers that separately."""
    injected = chron is not None
    token = auth_token if auth_token is not None else (None if injected else load_or_create_token())

    @asynccontextmanager
    async def lifespan(a: FastAPI) -> AsyncIterator[None]:
        if injected:
            a.state.chron = chron
            a.state.manager = manager
            a.state.platform = None
            yield
        else:
            platform = await build_platform()
            await reconcile_orphans(platform.chronicle)  # fix realms left "running" by a restart
            # ...and destroy the CONTAINERS that restart left behind. reconcile_orphans only made
            # the DATABASE honest: it marked the realm "interrupted" while its agents kept running,
            # holding live model keys, with nobody watching. Nothing is active at startup, so this
            # sweeps every leftover.
            reaped = platform.forge.reap_orphans(active=())
            if reaped:
                log.warning("reaped %d orphaned agent container(s): %s", len(reaped),
                            ", ".join(sorted(reaped)))
            a.state.platform = platform
            a.state.chron = platform.chronicle
            a.state.manager = RealmManager(platform)
            try:
                yield
            finally:
                await a.state.manager.shutdown()
                # a clean shutdown concludes each realm, which tears its agents down — but a realm
                # that fails to conclude must not leave them running either.
                with contextlib.suppress(Exception):
                    platform.forge.reap_orphans(active=())
                await platform.close()

    app = FastAPI(title="AgentRealm", lifespan=lifespan)

    # This origin has no authentication (see #105) and can start realms, spend money, and read
    # every transcript, private note and revealed submission. It binds to loopback by default, but
    # loopback alone stops neither of the two ways a web page reaches it:
    #
    #   DNS rebinding — attacker.example resolves to 127.0.0.1, so the browser connects locally
    #     while believing it is same-origin. The Host header still says attacker.example, so an
    #     allowlist rejects it.
    #   Cross-site form POST — /stop and /rerun take no body, so a plain HTML form on any page
    #     reaches them with no preflight. Requests from another origin are refused below.
    app.add_middleware(TrustedHostMiddleware, allowed_hosts=_allowed_hosts())

    @app.middleware("http")
    async def _require_token(request: Request, call_next: Any) -> Response:
        """Gate /api/* on the local token, and let `/?token=…` exchange it for a cookie.

        The exchange is what makes this usable from a browser without a login form: `arealm serve`
        prints the URL with the token in it, opening it stores an HttpOnly SameSite=Strict cookie,
        and the console then works normally. Scripts send `Authorization: Bearer <token>`."""
        if token is None:
            return await call_next(request)  # type: ignore[no-any-return]

        path = request.url.path
        supplied = presented_token(
            header=request.headers.get("authorization"),
            cookie=request.cookies.get(COOKIE_NAME),
            query=request.query_params.get(QUERY_PARAM),
        )
        if not is_public_path(path) and not token_matches(token, supplied):
            return JSONResponse(
                {"detail": "missing or invalid API token — see the URL printed by `arealm serve`"},
                status_code=401,
            )
        response: Response = await call_next(request)
        # A correct token on the console page becomes a cookie, so it need not stay in the URL.
        if path == "/" and token_matches(token, request.query_params.get(QUERY_PARAM)):
            response.set_cookie(
                COOKIE_NAME, token, httponly=True, samesite="strict", path="/",
                max_age=60 * 60 * 24 * 30,
            )
        return response

    @app.middleware("http")
    async def _block_cross_site_writes(request: Request, call_next: Any) -> Response:
        if request.method not in ("GET", "HEAD", "OPTIONS"):
            origin = request.headers.get("origin")
            # A same-origin fetch sends no Origin (or its own); a cross-site form POST sends the
            # attacker's. Sec-Fetch-Site is checked too where the browser provides it.
            if (origin and origin != str(request.base_url).rstrip("/")) or \
                    request.headers.get("sec-fetch-site") in ("cross-site", "same-site"):
                return JSONResponse({"detail": "cross-site request refused"}, status_code=403)
        response: Response = await call_next(request)
        return response

    def get_chron() -> Chronicle:
        return app.state.chron  # type: ignore[no-any-return]

    def get_manager() -> RealmManager:
        return app.state.manager  # type: ignore[no-any-return]

    def _static(name: str) -> str:
        """Read a UI asset from the static dir. Read fresh each call (the files are tiny) so a UI
        edit shows up without a server restart. Returns "" if absent."""
        f = STATIC_DIR / name
        return f.read_text() if f.is_file() else ""

    # The UI ships as a few unversioned files that change often, so tell browsers never to cache
    # them — otherwise a reload keeps serving stale app.js and fixes appear not to land.
    _NO_CACHE = {"Cache-Control": "no-store, max-age=0"}

    @app.get("/", response_class=HTMLResponse)
    async def dashboard() -> Response:
        # No fallback UI. There used to be a second, older console embedded in Python that served
        # whenever index.html was missing — but index.html ships with the package, so the fallback
        # never ran and quietly rotted. A missing asset is now a visible failure, not a different
        # and stale interface.
        html = _static("index.html")
        if not html:
            raise HTTPException(status_code=500, detail=f"UI assets missing from {STATIC_DIR}")
        return Response(html, media_type="text/html", headers=_NO_CACHE)

    @app.get("/static/app.css")
    async def app_css() -> Response:
        return Response(_static("app.css"), media_type="text/css", headers=_NO_CACHE)

    @app.get("/static/app.js")
    async def app_js() -> Response:
        return Response(_static("app.js"), media_type="application/javascript", headers=_NO_CACHE)

    @app.get("/health")
    async def health() -> dict[str, str]:
        return {"status": "ok"}

    @app.get("/api/realms")
    async def list_realms() -> dict[str, Any]:
        ids = await get_chron().realms()
        mgr = get_manager()
        active = set(mgr.active())
        return {
            "realms": [{"realm_id": r, "active": r in active} for r in ids],
            "active": len(active), "capacity": mgr.max_active,
        }

    @app.get("/api/packages")
    async def list_packages() -> dict[str, Any]:
        """Scenario packages available to run — user scenarios + bundled examples (folders with a
        project.json). A user scenario shadows a bundled example of the same name. Each entry
        carries light metadata (read from project.json, no full validation) for the card list."""
        user_dir = str(_import_base())
        seen: dict[str, dict[str, Any]] = {}
        for base in _scenario_bases():
            if not base.is_dir():
                continue
            for d in sorted(base.iterdir()):
                if not (d / "project.json").exists() or d.name in seen:
                    continue
                meta: dict[str, Any] = {}
                try:
                    meta = json.loads((d / "project.json").read_text()).get("metadata", {}) or {}
                except (OSError, json.JSONDecodeError):
                    meta = {}
                agents_dir = d / "agents"
                n_agents = sum(
                    1 for a in agents_dir.iterdir() if (a / "agent.json").exists()
                ) if agents_dir.is_dir() else 0
                seen[d.name] = {
                    "name": d.name, "path": str(d),
                    "title": meta.get("name") or d.name,
                    "description": meta.get("description") or "",
                    "tags": meta.get("tags") or [],
                    "category": meta.get("category") or "",
                    "agents": n_agents,
                    "editable": str(base) == user_dir,  # user scenarios can be edited/deleted
                }
        return {"packages": sorted(seen.values(), key=lambda p: p["name"])}

    @app.get("/api/packages/{name}")
    async def package_detail(name: str) -> dict[str, Any]:
        """Full details of one scenario for the preview page (config + roster)."""
        if "/" in name or ".." in name:
            raise HTTPException(status_code=400, detail="invalid scenario name")
        path = _find_scenario(name)
        if path is None:
            raise HTTPException(status_code=404, detail=f"no scenario {name!r}")
        try:
            project = load_package(str(path))
        except PackageError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        return serialize_project(project, name, str(path))

    @app.post("/api/packages/import")
    async def import_scenario(files: list[UploadFile] = File(...)) -> dict[str, Any]:
        """Import a scenario project FOLDER (uploaded via a directory picker) into the scenario
        list. Reconstructs the folder, validates it, and stores it under the imports dir."""
        import re
        import shutil

        if not files or len(files) > 500:
            raise HTTPException(status_code=400, detail="select one scenario folder")
        roots = {(f.filename or "").split("/")[0] for f in files if "/" in (f.filename or "")}
        if len(roots) != 1:
            raise HTTPException(status_code=400, detail="select a single scenario folder")
        root = roots.pop()
        name = re.sub(r"[^a-z0-9-]+", "-", root.lower()).strip("-")
        if not name:
            raise HTTPException(status_code=400, detail="invalid folder name")

        dest = _import_base() / name
        if dest.exists():
            shutil.rmtree(dest)
        dest.mkdir(parents=True, exist_ok=True)
        total = 0
        try:
            for f in files:
                parts = [p for p in (f.filename or "").split("/") if p and p not in (".", "..")]
                if len(parts) < 2 or parts[0] != root:
                    continue  # skip anything outside the selected folder
                data = await f.read()
                total += len(data)
                if total > 5_000_000:
                    raise HTTPException(status_code=413, detail="scenario folder too large (>5MB)")
                target = dest.joinpath(*parts[1:])
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(data)
            project = load_package(str(dest))
        except HTTPException:
            shutil.rmtree(dest, ignore_errors=True)
            raise
        except Exception as exc:
            shutil.rmtree(dest, ignore_errors=True)
            raise HTTPException(status_code=400, detail=f"not a valid scenario: {exc}") from exc
        return {"name": name, "title": project.metadata.name, "agents": len(project.agents)}

    # --- scenario authoring (create / edit / delete / zip) -------------------
    @app.post("/api/packages")
    async def create_package(data: dict[str, Any] = _JSON_BODY) -> dict[str, Any]:
        """Create a scenario from the editor payload (metadata + spec + agents)."""
        try:
            return sc.write_scenario(_import_base(), data.get("metadata", {}).get("name", ""), data)
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @app.put("/api/packages/{name}")
    async def update_package(name: str, data: dict[str, Any] = _JSON_BODY) -> dict[str, Any]:
        """Save edits to a scenario. Edits always write to the user dir, shadowing any bundled
        example of the same name (so the templates in examples/ are never mutated)."""
        if not sc.NAME_RE.match(name):
            raise HTTPException(status_code=400, detail="invalid scenario name")
        try:
            return sc.write_scenario(_import_base(), name, data)
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @app.delete("/api/packages/{name}")
    async def delete_package(name: str) -> dict[str, str]:
        """Delete a user scenario. Bundled examples are read-only templates and can't be deleted;
        deleting an edited copy just reveals the original example again."""
        try:
            sc.delete_scenario(_import_base(), name)
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        return {"deleted": name}

    @app.get("/api/packages/{name}/export")
    async def export_package(name: str) -> Response:
        """Download a scenario as a .zip (re-importable folder)."""
        if not sc.NAME_RE.match(name):
            raise HTTPException(status_code=400, detail="invalid scenario name")
        path = _find_scenario(name)
        if path is None:
            raise HTTPException(status_code=404, detail=f"no scenario {name!r}")
        return Response(
            sc.export_zip(path), media_type="application/zip",
            headers={"Content-Disposition": f'attachment; filename="{name}.zip"'},
        )

    @app.post("/api/packages/import-zip")
    async def import_package_zip(file: UploadFile = File(...)) -> dict[str, Any]:
        """Import a scenario from an uploaded .zip file."""
        try:
            return sc.import_zip(_import_base(), await file.read())
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    # --- skill library -------------------------------------------------------
    @app.get("/api/skills")
    async def list_skills() -> dict[str, Any]:
        return {"skills": sc.list_skills()}

    @app.get("/api/skills/{source}/{ref}")
    async def get_skill(source: str, ref: str) -> dict[str, Any]:
        content = sc.skill_content(source, ref)
        if content is None:
            raise HTTPException(status_code=404, detail=f"no skill {source}:{ref}")
        # `files` lists every bundled file (SKILL.md + scripts/references/assets) for the browser
        return {"source": source, "ref": ref, "content": content,
                "files": sc.skill_tree(source, ref)}

    @app.get("/api/skills/{source}/{ref}/file")
    async def get_skill_file(source: str, ref: str, path: str) -> dict[str, Any]:
        """Text content of one bundled file inside a skill (for the file browser)."""
        content = sc.read_skill_file(source, ref, path)
        if content is None:
            raise HTTPException(status_code=404, detail="file not found or not text")
        return {"path": path, "content": content}

    @app.post("/api/skills")
    async def create_skill(data: dict[str, Any] = _JSON_BODY) -> dict[str, Any]:
        try:
            return sc.write_custom_skill(str(data.get("name", "")), str(data.get("content", "")),
                                         data.get("category"))
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @app.post("/api/skills/import-gh")
    async def import_skill_gh(data: dict[str, Any] = _JSON_BODY) -> dict[str, Any]:
        try:
            return await sc.import_gh_skill(str(data.get("url", "")), data.get("name"))
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @app.post("/api/skills/import-file")
    async def import_skill_file(file: UploadFile = File(...)) -> dict[str, Any]:
        """Import a single-file skill from an uploaded SKILL.md."""
        try:
            content = (await file.read()).decode("utf-8", errors="replace")
            return sc.import_skill_file(file.filename or "skill.md", content)
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @app.post("/api/skills/import-zip")
    async def import_skill_zip(file: UploadFile = File(...)) -> dict[str, Any]:
        """Import an Agent Skill packaged as a .zip (SKILL.md + scripts/references/assets)."""
        try:
            return sc.import_skill_zip(await file.read())
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @app.post("/api/skills/import-folder")
    async def import_skill_folder(files: list[UploadFile] = File(...)) -> dict[str, Any]:
        """Import an Agent Skill from an uploaded folder (SKILL.md + bundled files)."""
        if len(files) > 500:
            raise HTTPException(status_code=400, detail="too many files")
        try:
            entries = [(f.filename or "", await f.read()) for f in files]
            return sc.import_skill_folder(entries)
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @app.get("/api/skills/{source}/{ref}/export")
    async def export_skill(source: str, ref: str) -> Response:
        """Download a skill as a .zip folder (SKILL.md + any bundled files)."""
        try:
            data = sc.export_skill_zip(source, ref)
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        return Response(
            data, media_type="application/zip",
            headers={"Content-Disposition": f'attachment; filename="{sc._slug(ref)}.zip"'},
        )

    @app.delete("/api/skills/{ref}")
    async def delete_skill(ref: str) -> dict[str, str]:
        try:
            sc.delete_custom_skill(ref)
        except sc.ScenarioError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        return {"deleted": ref}

    # --- Scribe: guided scenario authoring (#66, #73, #75) ---------------------
    # One session per wizard/edit conversation, created by POST /api/scribe/session (ids are
    # server-generated). Conversations PERSIST per scenario (spec §19): edit sessions bind on
    # open and resume the stored history; create sessions bind at approve. Live edit sessions
    # are also keyed by scenario, so revisiting an assist page resumes the SAME session instead
    # of minting an orphan. In UI mode the model NEVER writes: create-mode drafts land via
    # /api/scribe/approve, edit-mode drafts via the editor's PUT — both deterministic, no model
    # call. Scribe uses the SAME user scenarios dir the dashboard launches from, so an approved
    # scenario appears in the Scenarios list at once.
    @dataclass
    class _ScribeConn:
        session: ScribeSession
        mode: str  # "create" | "edit"
        store: PackageStore

    _scribe: dict[str, _ScribeConn] = {}
    _scribe_edit: dict[str, str] = {}  # scenario -> live edit session id (for session reuse)

    _CREATE_OPENING = (
        "Give me a short description of the scenario you want to build — what happens, "
        "who's in it, and how it ends."
    )

    def _scribe_data_root() -> Path:
        return scribe_root or Path.home() / ".agentrealm" / "scribe"

    def _new_scribe_loop(mode: str) -> tuple[ScribeLoop, PackageStore]:
        base_url = os.environ.get("SCRIBE_API_BASE", "http://127.0.0.1:4000/v1")
        api_key = os.environ.get("SCRIBE_API_KEY", "")
        store: PackageStore = scribe_store or ApiPackageStore(
            user_dir=_import_base(), example_dirs=[_scenario_bases()[1]]
        )
        loop = build_scribe(
            base_url, _scribe_data_root(), backend=scribe_backend, store=store,
            api_key=api_key, model=os.environ.get("SCRIBE_MODEL") or DEFAULT_MODEL,
            mode=mode
        )
        return loop, store

    @app.post("/api/scribe/session")
    async def scribe_session_create(req: ScribeSessionCreate) -> dict[str, Any]:
        """Open a guided authoring session. Deterministic — NO model call: the opening question
        is canned, and edit mode just loads the scenario for context + the preview pane. An edit
        request for a scenario with a live session returns THAT session (with its visible
        history) rather than minting a new one; otherwise the stored history is resumed."""
        sid = "s-" + secrets.token_hex(8)
        if req.mode == "create":
            loop, store = _new_scribe_loop("guided-create")
            session = ScribeSession(loop, history_store=HistoryStore(_scribe_data_root()))
            _scribe[sid] = _ScribeConn(session, "create", store)
            return {
                "session_id": sid,
                "opening": {"kind": "question", "text": _CREATE_OPENING, "options": []},
            }
        if req.mode == "edit":
            name = req.scenario or ""
            opening = {
                "kind": "question",
                "text": f"What would you like to change about {name!r}?",
                "options": [],
            }

            async def _manifest(store: PackageStore) -> dict[str, Any]:
                try:
                    project = await store.read(name)
                except (FileNotFoundError, KeyError, PackageError) as exc:
                    raise HTTPException(status_code=404, detail=f"no scenario {name!r}") from exc
                return project.model_dump(mode="json", by_alias=True, exclude_none=True)

            live_sid = _scribe_edit.get(name)
            live = _scribe.get(live_sid) if live_sid else None
            if live is not None and live_sid is not None:  # resume the live session as-is
                return {
                    "session_id": live_sid,
                    "opening": opening,
                    "package": await _manifest(live.store),
                    "history": visible_history(live.session.history),
                }
            loop, store = _new_scribe_loop("guided-edit")
            manifest = await _manifest(store)
            note = f"Current scenario {name!r}:\n{json.dumps(manifest, indent=2)}"
            session = await ScribeSession.resume(
                loop,
                scenario=name,
                history_store=HistoryStore(_scribe_data_root()),
                context_note=note,
            )
            _scribe[sid] = _ScribeConn(session, "edit", store)
            _scribe_edit[name] = sid
            return {
                "session_id": sid,
                "opening": opening,
                "package": manifest,
                "history": visible_history(session.history),
            }
        raise HTTPException(status_code=400, detail="mode must be 'create' or 'edit'")

    @app.post("/api/scribe/message")
    async def scribe_message(req: ScribeMessage) -> StreamingResponse:
        """Stream one Scribe turn as newline-delimited JSON LoopEvents (kind/text/name) so the
        wizard can show tool activity, questions, drafts, and the final reply live."""
        conn = _scribe.get(req.session_id)
        if conn is None:
            raise HTTPException(status_code=404, detail="unknown session — open one first")
        session = conn.session

        async def gen() -> AsyncIterator[bytes]:
            try:
                async for ev in session.send(req.text):
                    line = json.dumps({"kind": ev.kind, "text": ev.text, "name": ev.name})
                    yield (line + "\n").encode()
            except Exception as exc:  # surface a failed turn instead of a dead stream
                logging.exception("scribe turn failed")
                yield (json.dumps({"kind": "error", "text": str(exc)}) + "\n").encode()

        return StreamingResponse(gen(), media_type="application/x-ndjson")

    @app.post("/api/scribe/approve")
    async def scribe_approve(req: ScribeApprove) -> dict[str, Any]:
        """Write a create-session's stashed draft. Deterministic — NO model call. Edit sessions
        save through the editor's PUT instead."""
        conn = _scribe.get(req.session_id)
        if conn is None:
            raise HTTPException(status_code=404, detail="unknown session")
        if conn.mode != "create":
            raise HTTPException(
                status_code=409,
                detail="approve applies to create sessions; edit sessions save via "
                "PUT /api/packages/{name}",
            )
        draft = conn.session.draft
        if draft is None:
            raise HTTPException(status_code=409, detail="no draft to approve yet")
        try:  # belt-and-braces: the draft was validated at propose time; re-check before writing
            project = Project.model_validate(draft)
        except ValidationError as exc:
            raise HTTPException(
                status_code=400, detail=f"draft no longer validates: {exc}"
            ) from exc
        result = scribe_validate(project)
        if not result.ok:
            raise HTTPException(
                status_code=400, detail="draft no longer validates: " + "; ".join(result.errors)
            )
        name = sc._slug(project.metadata.name)
        if not name:
            raise HTTPException(status_code=400, detail="draft has no usable metadata.name")
        if await conn.store.has_user(name):
            raise HTTPException(
                status_code=409,
                detail=f"a scenario named {name!r} already exists — ask the assistant for a "
                "different name, or edit the existing one",
            )
        versions = Versions(_scribe_data_root() / "versions")
        await versions.snapshot(name, None)  # pre-create snapshot, same as the CLI write path
        await conn.store.write(name, project)
        # the wizard conversation attaches to the new scenario (§19) — a later "Edit with
        # assistant" resumes the authoring context
        await conn.session.bind(name)
        return {"name": name}

    @app.delete("/api/scribe/history/{scenario}")
    async def scribe_history_delete(scenario: str) -> dict[str, Any]:
        """Start fresh (§19): delete the stored history AND drop any live session bound to the
        scenario. 404 when the scenario has neither."""
        hstore = HistoryStore(_scribe_data_root())
        try:
            had_file = await hstore.has(scenario)
        except ValueError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        live = [s for s, c in _scribe.items() if c.session.scenario == scenario]
        if not had_file and not live:
            raise HTTPException(status_code=404, detail=f"no history for {scenario!r}")
        for s in live:
            _scribe.pop(s, None)
        _scribe_edit.pop(scenario, None)
        await hstore.delete(scenario)
        return {"deleted": scenario}

    @app.post("/api/scribe/history/{scenario}/summarize")
    async def scribe_history_summarize(scenario: str) -> dict[str, Any]:
        """Summarize now (§19): collapse the whole thread to the LLM summary immediately —
        the live session's history when one exists, else the stored file — save, and return
        the new visible thread. 404 when the scenario has neither."""
        hstore = HistoryStore(_scribe_data_root())
        live = next(
            (c for c in _scribe.values() if c.session.scenario == scenario), None
        )
        if live is not None:
            await live.session.compact_now()
            return {"history": visible_history(live.session.history)}
        try:
            had_file = await hstore.has(scenario)
        except ValueError as exc:
            raise HTTPException(status_code=404, detail=str(exc)) from exc
        if not had_file:
            raise HTTPException(status_code=404, detail=f"no history for {scenario!r}")
        loop, _ = _new_scribe_loop("guided-edit")
        history = await hstore.load(scenario)
        history = await compact(history, loop.backend, loop.model, keep_tail=0)
        await hstore.save(scenario, history)
        return {"history": visible_history(history)}

    # --- run history (enriched) + settings -----------------------------------
    @app.get("/api/runs")
    async def list_runs(scenario: str | None = None, limit: int = 300) -> dict[str, Any]:
        """Every past + live run with its state, outcome, spend and last-activity time — the
        history view. Scenario is derived from the realm id (auto ids carry a -hex6 suffix)."""
        chron = get_chron()
        active = set(get_manager().active())
        runs: list[dict[str, Any]] = []
        for rid in await chron.realms():
            events = await chron.events(rid)
            if not events:
                continue
            lifecycle = [e for e in events if e.kind == EventKind.LIFECYCLE]
            state = lifecycle[-1].payload.get("event") if lifecycle else "unknown"
            outcome, spend = None, 0.0
            for e in events:
                if e.kind == EventKind.VERDICT:
                    outcome = e.payload.get("outcome", outcome)
                elif e.kind == EventKind.SPEND:
                    spend += float(e.payload.get("usd", 0))
            is_active = rid in active
            if not is_active and state in NON_TERMINAL:
                state = "interrupted"
            runs.append({
                "realm_id": rid, "scenario": re.sub(r"-[0-9a-f]{6}$", "", rid),
                "state": state, "outcome": outcome, "spend": round(spend, 4),
                "updated": max(e.ts_ms for e in events), "active": is_active,
            })
        if scenario:
            runs = [r for r in runs if r["scenario"] == scenario]
        runs.sort(key=lambda r: r["updated"], reverse=True)
        return {"runs": runs[:limit], "capacity": get_manager().max_active, "active": len(active)}

    @app.get("/api/settings")
    async def settings() -> dict[str, Any]:
        """App-level configuration: capacity, key handles (names only), library sizes, versions.
        Key handles are the plaintext dict keys of the keystore — never the secret values."""
        from importlib.metadata import PackageNotFoundError, version

        from agentrealm.forge.skills import BUILTIN_SKILLS

        key_refs: list[str] = []
        ks = Path.home() / ".agentrealm" / "keystore.json"
        if ks.exists():
            try:
                data = json.loads(ks.read_text())
                key_refs = sorted(data.keys()) if isinstance(data, dict) else []
            except (OSError, json.JSONDecodeError):
                key_refs = []
        try:
            ver = version("agentrealm")
        except PackageNotFoundError:
            ver = "dev"
        n_custom = len([s for s in sc.list_skills() if s["source"] == "local"])
        n_scen = sum(
            1 for b in _scenario_bases() if b.is_dir()
            for d in b.iterdir() if (d / "project.json").exists()
        )
        # the model pipeline: which provider agents run on, each provider's editable category tables
        # (small/medium/large -> model + effort + costs + context), and readiness (keystore handle)
        from agentrealm.gatekeeper.appstate import active_provider, providers_config

        cfg = providers_config()
        model_providers = []
        for name, prof in cfg.items():
            need = str(prof.get("api_key_ref") or "")
            model_providers.append({
                "name": name,
                "label": prof.get("label") or name,
                "description": prof.get("description") or "",
                "api_key_ref": need,
                "ready": need in key_refs,  # the keystore handle exists
                "needs_key_ref": need if need not in key_refs else None,
                "setup_hint": prof.get("setup_hint") or "",
                "flat_rate": bool(prof.get("flat_rate")),
                "min_budget_usd": prof.get("min_budget_usd"),
                "min_turn_seconds": prof.get("min_turn_seconds"),
                "categories": prof.get("categories") or {},
            })
        return {
            "version": ver,
            "capacity": get_manager().max_active,
            "active": len(get_manager().active()),
            "api_key_refs": key_refs,
            "skills_builtin": len(BUILTIN_SKILLS),
            "skills_custom": n_custom,
            "scenarios": n_scen,
            "scenarios_dir": str(_import_base()),
            "examples_dir": str(_scenario_bases()[1]),
            "model_categories": ["small", "medium", "large"],
            "model_provider": active_provider(),
            "model_providers": model_providers,
        }

    @app.put("/api/settings/provider")
    async def set_provider(data: dict[str, Any] = _JSON_BODY) -> dict[str, Any]:
        """Switch the active model pipeline for ALL scenarios at once. Applied at launch time — no
        manifest is changed, so it's an instant, reversible toggle."""
        from agentrealm.gatekeeper.appstate import active_provider, set_active_provider

        name = str(data.get("model_provider") or data.get("provider") or "")
        try:
            set_active_provider(name)
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        return {"model_provider": active_provider()}

    @app.put("/api/settings/model-config")
    async def set_model_config(data: dict[str, Any] = _JSON_BODY) -> dict[str, Any]:
        """Edit the provider tables: for each provider, the model + effort + costs + context per
        category (small/medium/large), and its api_key_ref."""
        from agentrealm.gatekeeper.appstate import providers_config, set_providers_config

        raw = data.get("providers")
        providers: dict[str, Any] = raw if isinstance(raw, dict) else data
        try:
            set_providers_config(providers)
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        return {"model_providers": providers_config()}

    @app.post("/api/realms")
    async def create_realm(req: CreateRealm) -> dict[str, Any]:
        try:
            project = load_package(req.package)
        except (PackageError, FileNotFoundError) as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        if req.turns is not None:  # UI override: enable/disable turns for this run
            turns = (
                Turns(silence_timeout_s=req.turns.silence_timeout_s)
                if req.turns.enabled else None
            )
            project = project.model_copy(
                update={"spec": project.spec.model_copy(update={"turns": turns})}
            )
        import re
        import secrets

        base = re.sub(r"[^a-z0-9-]+", "-", project.metadata.name.lower()).strip("-") or "realm"
        realm_id = req.realm_id or f"{base}-{secrets.token_hex(3)}"
        # Mention policy: the scenario may opt into free-response (require_mention=false) so agents
        # reply by relevance instead of being FORCED to answer every @mention — the latter makes
        # mini-models ping-pong "acknowledged" forever in group games. The request flag can also
        # force it on. Either source wins.
        require_mention = project.spec.environment.require_mention and not req.free_response
        try:
            get_manager().start(realm_id, project, require_mention=require_mention)
        except CapacityError as exc:
            raise HTTPException(status_code=429, detail=str(exc)) from exc
        except ValueError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc
        return {"realm_id": realm_id, "state": "starting"}

    @app.get("/api/realms/{realm_id}")
    async def get_realm(realm_id: str) -> dict[str, Any]:
        status = await realm_status(get_chron(), realm_id)
        run = get_manager().runs.get(realm_id)
        status["active"] = realm_id in get_manager().active()
        status["error"] = run.error if run else None
        if status["error"] and status["state"] not in ("archived", "failed"):
            status["state"] = "failed"  # a crashed run must not read as still "provisioning"
        elif not status["active"] and status["state"] in NON_TERMINAL:
            # a non-terminal state with no live task = the run was cut off (e.g. server restart)
            status["state"] = "interrupted"
        return status

    @app.get("/api/realms/{realm_id}/transcript")
    async def transcript(realm_id: str, limit: int = 200) -> dict[str, Any]:
        msgs = await get_chron().messages(realm_id)
        # channel_id -> label so the UI can tag private DM threads. The commons + side-channel room
        # ids are recorded on the 'running' lifecycle event at provision time.
        channels: dict[str, str] = {}
        lifecycle = await get_chron().events(realm_id, kind=EventKind.LIFECYCLE)
        run = next((e.payload for e in reversed(lifecycle) if e.payload.get("commons_room")), None)
        if run:
            channels[run["commons_room"]] = "commons"
            for room, label in (run.get("side_channels") or {}).items():
                channels[room] = label
        return {"channels": channels, "messages": [
            {"ts": m.ts_ms, "channel": m.channel, "sender": m.sender, "body": m.body}
            for m in msgs[-limit:]
        ]}

    @app.get("/api/realms/{realm_id}/events")
    async def realm_events(
        realm_id: str, kind: str | None = None, limit: int = 200
    ) -> dict[str, Any]:
        """The realm's chronicled events (TURN grants, VERDICT, SPEND, LIFECYCLE, …) — the
        debugging timeline the transcript alone can't show (e.g. who actually held the floor when,
        whether a verdict was ever recorded). `kind` filters (e.g. ?kind=turn)."""
        evs = await get_chron().events(realm_id, kind=kind)
        return {"events": [
            {"ts": e.ts_ms, "kind": e.kind, "payload": e.payload} for e in evs[-limit:]
        ]}

    @app.get("/api/realms/{realm_id}/report")
    async def report(realm_id: str) -> Response:
        """The final report as Markdown — deliberately NOT text/html.

        `final_report` embeds referee-authored strings verbatim (the verdict outcome, each
        violation's reason). Those are raw model output produced after reading agent chat, which
        an agent can influence. Serving them as HTML on this origin would let an injected verdict
        run same-origin JavaScript against every other endpoint here — the realm→host crossing
        `docs/architecture.md` §16 says must be impossible. Rendering is the client's job.
        """
        md = await get_chron().final_report(realm_id, title=f"Realm {realm_id}")
        return Response(md, media_type="text/markdown; charset=utf-8",
                        headers={"X-Content-Type-Options": "nosniff"})

    @app.post("/api/realms/{realm_id}/rerun")
    async def rerun_realm(realm_id: str, mode: str = "snapshot") -> dict[str, Any]:
        """Run this realm again. Two honestly-different things, and the caller must choose.

        mode="snapshot" (a REPLAY) — restores the resolved project captured when that run started:
            the same models, efforts, budgets, turn floor, personas and rubrics. It deliberately
            does NOT re-read the scenario file and does NOT re-resolve against the active provider,
            because either may have changed since. Edits made afterwards are NOT picked up.

        mode="latest" — reloads the scenario from its package and resolves it against the CURRENT
            settings. This is a DIFFERENT run: newer personas, whatever provider is active now, and
            any platform changes. Use it to test a fix; use "snapshot" to reproduce a result.

        Conflating the two is how you "reproduce" a bug against code that no longer has it.
        """
        import re
        import secrets

        from agentrealm.gatekeeper.runner import project_from_snapshot

        if mode not in ("snapshot", "latest"):
            raise HTTPException(status_code=400, detail="mode must be 'snapshot' or 'latest'")

        events = await get_chron().events(realm_id, kind=EventKind.LIFECYCLE)
        snap = next((e.payload for e in events if e.payload.get("project")), None)
        if snap is None:
            raise HTTPException(
                status_code=409,
                detail="this realm ran before its configuration was captured — launch the scenario "
                       "from the Scenarios page instead",
            )

        if mode == "snapshot":
            project = project_from_snapshot(dict(snap["project"]))
            require_mention = bool(snap.get("require_mention", True))
        else:
            package = snap.get("package")
            if not package:
                raise HTTPException(
                    status_code=409,
                    detail="the scenario this ran from is no longer on record — replay the "
                           "snapshot, or launch it from the Scenarios page",
                )
            try:
                project = load_package(str(package))
            except (PackageError, FileNotFoundError) as exc:
                raise HTTPException(
                    status_code=409,
                    detail=f"scenario {package!r} can no longer be loaded ({exc}) — replay the "
                           f"snapshot instead",
                ) from exc
            require_mention = project.spec.environment.require_mention

        base = re.sub(r"[^a-z0-9-]+", "-", project.metadata.name.lower()).strip("-") or "realm"
        new_id = f"{base}-{secrets.token_hex(3)}"
        try:
            get_manager().start(new_id, project, require_mention=require_mention)
        except CapacityError as exc:
            raise HTTPException(status_code=429, detail=str(exc)) from exc
        except ValueError as exc:
            raise HTTPException(status_code=409, detail=str(exc)) from exc
        return {"realm_id": new_id, "state": "starting", "rerun_of": realm_id, "mode": mode}

    @app.post("/api/realms/{realm_id}/stop")
    async def stop(realm_id: str) -> dict[str, str]:
        get_manager().stop(realm_id)
        return {"realm_id": realm_id, "state": "stopping"}

    @app.post("/api/realms/{realm_id}/msg")
    async def inject(realm_id: str, req: Inject) -> dict[str, str]:
        platform = app.state.platform
        events = await get_chron().events(realm_id, kind=EventKind.LIFECYCLE)
        room = next(
            (e.payload["commons_room"] for e in reversed(events) if e.payload.get("commons_room")),
            None,
        )
        if not room:
            raise HTTPException(status_code=404, detail="no live commons room for this realm")
        msgs = await get_chron().messages(realm_id)
        agents = sorted({m.sender for m in msgs if m.sender.startswith(f"@{realm_id}-")})
        # Everything posts to the shared commons (agents only listen on rooms created at birth, so a
        # mid-run private DM wouldn't reach them). `to` just changes who is ADDRESSED: one agent's
        # mxid/id -> mention + address only them; null -> mention everyone.
        mentions: list[str] | None
        if req.to:
            target = req.to if req.to in agents else next(
                (a for a in agents
                 if a.removeprefix(f"@{realm_id}-").split(":")[0] == req.to), None)
            if target is None:
                raise HTTPException(status_code=404, detail=f"no agent {req.to!r} in this realm")
            name = target.removeprefix(f"@{realm_id}-").split(":")[0]
            mentions, body = [target], f"[operator → {name}] {req.text}"
        else:
            mentions, body = (agents or None), f"[operator] {req.text}"
        await platform.herald.ensure_system(platform.system_password)
        await platform.herald.announce(str(room), body, mentions=mentions)
        return {"realm_id": realm_id, "posted": "ok", "to": req.to or "all"}

    return app


# Config is only read at startup (the lifespan builds the Platform), so constructing the app
# object at import time is safe — uvicorn fails with a clear ConfigError on `up` if unset.
app = create_app()
